name: ml-project-template

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ml-project-template-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    expose:
      - "6333"
      - "6334"
      - "6335"
    volumes:
      - qdrant-data:/qdrant_data
    restart: always

volumes:
  qdrant-data: